spring:
  application:
    name: 'orderflow'
  datasource:
    url: 'jdbc:mysql://localhost:3306/orderflow'
    username: 'root'
    password: '4586'
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQLDialect'

#Dev Only
management:
  endpoints:
    web:
      exposure:
        include: "*"