spring:
  application:
    name: 'orderflow'
  datasource:
    url: 'jdbc:mysql://localhost:3306/orderflow'
    username: 'root'
    password: '4586'
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQLDialect'

security:
  jwt:
    secret: 'this_is_a_random_secret_string_copied_again_to_increase_length_this_is_a_random_secret_string'
    expMinutes: 60

#Dev Only
management:
  endpoints:
    web:
      exposure:
        include: "*"